# Generated by Django 3.1.6 on 2021-02-13 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('korisnik', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kupac',
            },
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('cena', models.FloatField()),
                ('digital', models.BooleanField(default=False, null=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Proizvod',
            },
        ),
        migrations.CreateModel(
            name='Narudzbina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_narudzbine', models.DateTimeField(auto_now_add=True)),
                ('status_narudzbine', models.BooleanField(default=False, null=True)),
                ('id_transakcije', models.CharField(max_length=100, null=True)),
                ('kupac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodavnica.kupac')),
            ],
            options={
                'verbose_name_plural': 'Narudzbina',
            },
        ),
        migrations.CreateModel(
            name='NaruceniProizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('datum_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('narudzbina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodavnica.narudzbina')),
                ('proizvod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodavnica.proizvod')),
            ],
            options={
                'verbose_name_plural': 'NaruceniProizvod',
            },
        ),
        migrations.CreateModel(
            name='Dostava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=200)),
                ('grad', models.CharField(max_length=200)),
                ('drzava', models.CharField(max_length=200)),
                ('postanskibroj', models.CharField(max_length=200)),
                ('datum_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('kupac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodavnica.kupac')),
                ('narudzbina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodavnica.narudzbina')),
            ],
            options={
                'verbose_name_plural': 'Dostava',
            },
        ),
    ]
