# Generated by Django 3.1.6 on 2021-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='snizena_cena',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
