# Generated by Django 3.1.6 on 2021-02-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0002_proizvod_snizena_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='opis',
            field=models.CharField(default='Opis', max_length=400),
            preserve_default=False,
        ),
    ]
