# Generated by Django 3.1.6 on 2021-02-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0003_proizvod_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='opis',
            field=models.TextField(),
        ),
    ]
