# Generated by Django 3.1.6 on 2021-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0004_auto_20210214_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='slug',
            field=models.SlugField(default='test-proizvod'),
            preserve_default=False,
        ),
    ]
