# Generated by Django 3.1.6 on 2021-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0005_proizvod_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
