# Generated by Django 3.1.6 on 2021-02-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0006_auto_20210219_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvod',
            name='slug',
        ),
    ]
