# Generated by Django 3.1.6 on 2021-02-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0007_remove_proizvod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
