# Generated by Django 3.1.6 on 2021-03-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0010_auto_20210318_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kupac',
            options={'verbose_name_plural': 'Kupac'},
        ),
        migrations.RenameField(
            model_name='kupac',
            old_name='user',
            new_name='kupac',
        ),
    ]
